### ISSUE TITLE
Bug: Web - Invalid quick-start example

### ISSUE THREAD

**Issue by huytran46** [silenteer/submodule#3]
### Hi there!

On the web, we have a great, simple example - which is helpful for newcomers to quickly understand the intention and the idea behind the library.

Unfortunately, it has a small bug :)

We call the log() method in `mymodule.mjs` but we haven't defined the method in `main.mjs`

**Current:**

<img width="472" alt="image" src="https://github.com/submodule-js/submodule/assets/39490493/5465745e-781e-46a0-b4f6-ad1848093424">

**Proposal:**

Edit the `main.mjs` file

<img width="472" alt="image" src="https://github.com/submodule-js/submodule/assets/39490493/7f368220-8782-48e1-915e-92d785b13e88">

### Finally, thank you for this wonderful library!

**Comment by lagz0ne** [comment]
Hello,

Thanks for your contribution, we have updated the document (along with version 4 release)

Cheers
